#!/bin/sh

# combined script to prepare and carry out temperature logging with a single PT100 attached to an
#  agilent 34401A via 4-wire measurement via a Prologix GPIB adapter.

# device node for prologix thing
DEV=/dev/ttyUSB0

PROG=/home/qitlab/programs/getresponse/getresponse
# GPIB address
ADDR=22

# echo "++auto 0" >$DEV
# echo "++eoi 1" >$DEV
# echo "++eos 0" >$DEV

$PROG -n -d $DEV "++addr $ADDR\r"
$PROG -n -d $DEV "++auto 0"

# Eventually flush input buffer - and remove irritating carriage return
r=$($PROG -d $DEV "++spoll" |sed -e "s/\r//g")
if [ $r != "0" ]
then
#    echo "delay. response:"
#    echo -n $r |hexdump -C
    $PROG -d $DEV "++read" >/dev/null
    usleep 500000 ; # let the thing recover from this read
fi

# Call measurement
$PROG -d $DEV -n "meas:fres? 100,0.00001"

r="0"
# echo "first spoll repsonse: >$r<"
for (( i=0 ; ( $i<10 ) && ( $r == "0" ) ; i++ ))
do
#    echo "response: $i, >$r<"
#   echo -n $r |hexdump -C
   r=$($PROG -d $DEV "++spoll"|sed -e "s/\r//g")
   usleep 500000
done


# targt file for logs
TARGET=/home/qitlab/log/templog

# get date and measurement result...
a=$(date +"%F %T")
b=$($PROG -d $DEV "++read" |sed -e "s/\r//g")

# ... and append it to the log file
echo $a $b >>$TARGET
# echo $a $b
