# This is a script to generate a DDS control sequence with the dds_encode
# program. Pipe this into the dds_encode, and have the sequence either
# stored into a binary command file, or to the DDS chip directly.
# The latter can be done with cat calibrate.script >dds_encode
# Don't forget the full stop at the end ...
# Calibration is done with a 10 MHz and full output swing

Levels 2 ; Mode singletone
frequency 2 10 MHz
amplitude 2 1023
.

