# Setting up channel 0 for a linear frequency sweep in from 1 MHz to
# 10 MHz with a rise and fall rate of 10 MHz/sec
# the update rates are chosen to 20x (8nsec), resulting in
# a rise/fall word of 10MHz/sec*160nsec = 1.6Hz. Since the freq
# resolution is around 0.1 Hz, there is a significant uncertainty in the rise
# time

Levels 2
frequency 0 1 MHz
tuning 1 10 MHz
sweep FM 0 1.6 Hz 1.6 Hz 20 20
.
