#  Setting up channel 1 for a linear frequency sweep from 1 MHz to
#  100 MHz with a rise and fall rate of 20 MHz/sec.
#  the update rates are chosen to 20x (8nsec), resulting in
#  a rise/fall word of 20MHz/sec*160nsec = 3.2Hz. Since the freq
#  resolution is around 0.1 Hz, there is a significant uncertainty in the rise
#  time.

Levels 2
frequency 1 1 MHz
tuning 1 100 MHz
sweep FM 1 3.2 Hz 3.2 Hz 20 20
.

