#!/bin/bash
# script from robin

until autossh -M 0 -vv -f -N -R 2222:localhost:22 hcphotonics@infocommsociety.com; do
    echo "autossh crashed with exit code $?.  Respawning.." >&2
    sleep 1
done
