#!/usr/bin/perl

# This script generates the trend graphs for the temperature reading. It takes
# parameters "unit" (naming the unit) and "length" with values 0...4, 
# for day/week/month/quarter/year as arguments, passed by via GET method.


# Directories where the log files reside in
$logdir="/home/qitlab/log";
$gnudir="/home/qitlab/programs/logger";

# Image directory:
$imgdir="/srv/www/htdocs/img";

 
# Following http://www.tutorialspoint.com/perl/perl_cgi.htm, we extract the
# parameters sent via get:

local ($buffer, @pairs, $pair, $name, $value, %FORM);
# Read in text
$ENV{'REQUEST_METHOD'} =~ tr/a-z/A-Z/;
if ($ENV{'REQUEST_METHOD'} eq "GET")
{
    $buffer = $ENV{'QUERY_STRING'};
}
# Split information into name/value pairs
@pairs = split(/&/, $buffer);
foreach $pair (@pairs)
{
    ($name, $value) = split(/=/, $pair);
    $value =~ tr/+/ /;
    $value =~ s/%(..)/pack("C", hex($1))/eg;
    $FORM{$name} = $value;
}

# Extract the interesting ones
$timespan = $FORM{length};

# Generate page header
print "content-type: text/html\n\n";
print "<html><title>Mobile temperature logging server</title>
<style type=\"text/css\">\@import \"/css/cqtlog.css\";</style>
<body>\n";

# Now, we need to check for validity of the timespan entry
# test if we have proper value 0...3 for length
if ($timespan !~ /[0123]/) {
    # by default, take a week
    $timespan=1;
}
# For debugging
# $timespan=1;
# $core="AHU2";
    
# Prepare flexible arguments for gnuplot for different sizes
    @datapoints = ( 1500, 10800, 46000, 120000); 
    @samplingdensity = (1, 10, 30, 120);
    @outputformat = ("%m/%d\\n%H:%M", "%a\\n%m/%d\\n%H:%M", "%m/%d", "%d.%b");
    
    
    $imagename = "temp_".$datapoints[$timespan].".png";
    
# compose parameter set for gnuplot
    $parset="num=$datapoints[$timespan]; evr=$samplingdensity[$timespan]; ofmt=\"$outputformat[$timespan]\"; outfilename=\"$imagename\"; logdir=\"$logdir\"; imgdir=\"$imgdir\" \n";
    
# generate image
    open GNUPLOT, "| gnuplot - $gnudir/showtraceweb.gnu >/dev/null";
    print GNUPLOT $parset;
    close GNUPLOT;
    
# Generate web page
    print "<h1>Temperature log</h1>\n";
    print "<img src=\"/img/".$imagename."\">\n";
    
# Select other resolutions/ units
    print "<p>
<b>Show other time span:</b> 
<a href=\"/cgi-bin/showtemp?unit=$core&length=0\"> day</a> |
 <a href=\"/cgi-bin/showtemp?unit=$core&length=1\"> week </a> |
 <a href=\"/cgi-bin/showtemp?unit=$core&length=2\"> month</a> |
 <a href=\"/cgi-bin/showtemp?unit=$core&length=3\"> quarter</a></p>
";

# Link to main page of this server
print "<p>Back to <a href=\"/index.html\">main page</a>.</p>";

# Finish html page
print "</body>\n</html>\n";
