All: setclock playcpld gettrace

setclock: setclock.c
	gcc -Wall -O3 -o setclock setclock.c

playcpld: playcpld.c
	gcc -Wall -O3 -o playcpld playcpld.c

gettrace: gettrace.c
	gcc -Wall -O3 -o gettrace gettrace.c
