#!/bin/bash
out_file="150713b.dat"
getresponse="/home/qitlab/programs/getresponse/getresponse"

#if [-f $out_file ]
#then
#	rm $out_file
#fi

for ((i=0;i<=4000;i+=50))
do
outvalue=$(echo $i |awk '{print $0/1000}')
echo $outvalue
echo "OUT 0 $outvalue" > /dev/ttyUSB1 

measured_val=$($getresponse -d /dev/ttyUSB0 "MEAS?")

echo $outvalue" "$measured_val >> $out_file
sleep 1
done
